spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/classic_kitchen
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
